apiVersion: v1
kind: Service
metadata:
  name: health-api-service
  namespace: health-api
  labels:
    app: health-api
spec:
  selector:
    app: health-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

