apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api-deployment
  namespace: health-api
  labels:
    app: health-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-api
  template:
    metadata:
      labels:
        app: health-api
    spec:
      containers:
      - name: health-api
        image: guiiifsouza/health-api:1.1
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: health-api-secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

