apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: health-api-hpa
  namespace: health-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-api-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

